name: aq_schema
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  json_schema: ^5.0.0
  meta: ^1.17.0
  pub_semver: ^2.1.4
dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
